// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yszjfczmqlsqumnewqrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzempmY3ptcWxzcXVtbmV3cXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjY0ODAsImV4cCI6MjA2NjgwMjQ4MH0.91RF1WgV45A9nGzzwB99reIbe4gffnfHgXpD3LU0VlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});